### ISSUE TITLE
Unable to delete a value pasted from clipboard using backspace

### ISSUE THREAD

**Issue by s1n7ax** [nvim-telescope/telescope.nvim#1287]
### Description

* Copy a value to clipboard
* Paste the value to Telescope file search input (ctrl + shift + v)
* Hit backspace to remove the pasted value

The value can not be deleted using backspace. However you can use delete key to remove the value.

### Neovim version

NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5

### Operating system and version

Arch Linux

### checkhealth telescope

```markdown
health#telescope#check
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided
```

### Steps to reproduce

* Copy a value to clipboard
* Paste the value to Telescope file search input (ctrl + shift + v)
* Hit backspace to remove the pasted value

### Expected behavior

Delete the character in the left side of the cursor when backspace is pressed

### Actual behavior

The text will not change

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by elianiva** [comment]
have you tried [this PR](https://github.com/neovim/neovim/pull/15881)? I think it's related to prompt bug upstream

**Comment by praveendhawan** [comment]
It's still happening on nvim 0.6

**Comment by elianiva** [comment]
this has been fixed on master since https://github.com/neovim/neovim/pull/16421

**Comment by s1n7ax** [comment]
This issue is not fixed.

nvim: v0.6.0v0.6.0
telescope: 6b1579741a0e8f1e0e63d0c6c364b968c157338e (latest commit as of this comment)

I noticed that when the user is entered something using keyboard, characters can be passed and backspace work for that session. How ever when clipboard is pasted to new session, backspace doesn't work

**Comment by Conni2461** [comment]
Its fixed on latest neovim master. This commit is not part of the 0.6 release.

Closing because its fixed upstream. Just tested it.
