### ISSUE TITLE
expose prompt height

### ISSUE THREAD

**Issue by max397574** [nvim-telescope/telescope.nvim#1640]
I'd rly like to be able to set prompt height to two because then it would be possible to have the prompt centered like this:
![Screenshot 2021-12-29 at 15 10 54](https://user-images.githubusercontent.com/81827001/147670855-f42d7d23-88cd-47be-b00d-3c17a0489dc3.png)

(did this by just changing it in the source code)
This opens a problem with part of the border being before the prompt (similar to this: https://github.com/nvim-telescope/telescope.nvim/issues/1557)

**Comment by max397574** [comment]
I could also help implementing this I need guidance though.

**Comment by l-kershaw** [comment]
I don't understand what it is you are aiming for by setting the prompt height to 2.

Do you want to be able to input multiple lines as prompt? (I think that this will break lots of stuff)
Do you want to be able to have a border above, but not below? (I think that this should already be possible)

Could you explain a bit more?

**Comment by max397574** [comment]
basically padding above and below

**Comment by max397574** [comment]
If there is no reason not to do it I can open a pr (I've already implemented it)

**Comment by l-kershaw** [comment]
I'm still not sure what problem it is that you are trying to solve.
When you say "padding" do you mean something different to the current borders?

**Comment by max397574** [comment]
Compare the image I sent above to this:
![Screenshot_2021-12-29_at_13 59 12](https://user-images.githubusercontent.com/81827001/147675679-4a2b127d-00b8-4a25-99e2-104bd7b14db3.png)

**Comment by l-kershaw** [comment]
Oh, okay, you are using the `bottom_pane` layout.
This is a design choice of that layout, and other layouts don't have this.

**Comment by max397574** [comment]
could we implement it for the bottom_pane layout then?

**Comment by l-kershaw** [comment]
I think that this is a key part of the `bottom_pane` layout, and adding an option to configure this doesn't seem worth it in terms of added value compared to additional complexity (both complexity of code and complexity for users).

If you want to tweak a layout for you own personal use, then that is totally possible, as the layouts are just lua functions in a table, and can be overwritten easily.

**Comment by max397574** [comment]
okay I'd try that then
