### ISSUE TITLE
Filtered view has one last entry which is empty

### ISSUE THREAD

**Issue by OkanEsen** [nvim-telescope/telescope.nvim#231]
Filtered elements have one entry which is empty and selectable:

![2020-11-10_16-44](https://user-images.githubusercontent.com/552226/98696524-322e3680-2374-11eb-9414-9fbdc36c1c9b.png)

If I press enter on that empty entry this happens:
![2020-11-10_16-46](https://user-images.githubusercontent.com/552226/98696678-60137b00-2374-11eb-8ad8-83d0c7c22048.png)

Which in turn doesn't allow to remove the last character via backspace any more until any other key is pressed again, which triggers a new filter.

Video: https://i.imgur.com/Q5aicjd.mp4

**Comment by tjdevries** [comment]
I'm pretty sure I've fixed this now. If not, please re-open! Thanks

**Comment by OkanEsen** [comment]
Yep, seems to work, thanks! The second issue still persists though: just fill the input, until no entry is matched/visible and press enter. Cursors moves `len(input) - 1` and moving the cursor to the end and pressing backspace is prevented.

Video: https://i.imgur.com/srnllRo.mp4

Should I make a new issue for this?

**Comment by tjdevries** [comment]
New issue would be great. Thanks!
