### ISSUE TITLE
Filenames beginning with a +

### ISSUE THREAD

**Issue by milkias17** [nvim-telescope/telescope.nvim#2502]
### Description

Telescope can't open a file with a leading + symbol since + has a special meaning in vim.

### Neovim version

```markdown
NVIM v0.9.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmis
sing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=auto -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLAR
ATIONS -D_GNU_SOURCE -I/usr/include/luajit-2.1 -I/usr/include -I/usr/include/luajit-2.1 -I/builddir/build/BUILD/neovim-0.9.0/redhat-linux-build/src/nvim/auto -I/builddir/build/BUILD/neovim
-0.9.0/redhat-linux-build/include -I/builddir/build/BUILD/neovim-0.9.0/redhat-linux-build/cmake.config -I/builddir/build/BUILD/neovim-0.9.0/src -I/usr/include -I/usr/include -I/usr/include
 -I/usr/include -I/usr/include -I/usr/include -I/usr/include

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Linux 6.2.14

### Telescope version / branch / rev

telescope 0.1.1

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.7.0

===== Installed extensions ===== ~

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `media_files` ~
- No healthcheck provided
```

### Steps to reproduce

1. touch +page.svelte
2. vim
3. :Telescope find_files
4. Select the +page.svelte
5. Doesn't open!!

### Actual behavior

File doesn't open.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment]
This looks like a duplicate of https://github.com/nvim-telescope/telescope.nvim/issues/2446
In the linked issue, it appeared like it was a Windows issues but maybe it's not considering you're experiencing this on Linux.

But I can't replicate this on Linux, telescope v0.1.1.
What's the error message you're getting?

**Comment by Conni2461** [comment]
It should be fixed on latest master, i wanna wait one day until i'll backport to 0.1.x

**Comment by emilaleksanteri** [comment]
Do I need to update my telescope config to make the fix work for sveltekit projects? Still does not seem to work on mine on windows for some reason :(

**Comment by jamestrew** [comment]
This fix was backported to telescope v0.1.x so this should be working provided you've updated telescope.

**Comment by emilaleksanteri** [comment]
> This fix was backported to telescope v0.1.x so this should be working provided you've updated telescope.

Coolio, thank you!!
