### ISSUE TITLE
Respect winblend by default

### ISSUE THREAD

**Issue by anuramat** [nvim-telescope/telescope.nvim#2702]
**Is your feature request related to a problem? Please describe.**
Telescope doesn't respect `winblend` value

**Describe the solution you'd like**
Default value of `winblend = vim.o.winblend`, if none is set in `opts.defaults.winblend`.

**Describe alternatives you've considered**
- `opts.defaults.winblend = vim.o.winblend`: doesn't get updated if you set a new value after loading Telescope
- Wrapping every picker in something like
```lua
local function picker(name)
  return function()
    require('telescope.builtin')[name](require('telescope.themes').get_ivy({
      winblend = vim.o.winblend,
    }))
  end
end
```
Works fine, but then why have the defaults in the first place

**Additional context**
Not a big deal obviously, but `:Lazy`,`:LspInfo`,`:NullLsInfo` and [ThePrimeagen/harpoon](https://github.com/ThePrimeagen/harpoon)'s quick menu all do this by default, so I guess this would be the expected behaviour

**Comment by jamestrew** [comment]
This is a good suggestion and I would love to do this but this would cause a change in behavior/breaking change. It's a minor one but I'm a little bit hesitant.

**Comment by anuramat** [comment]
IMO this is almost a bug, and so the breaking change is fine; I mean how many people would like winblend only in *some* of the floating windows? Even then, it's not gonna suddenly make their setup completely unusable (unless they have winblend=100 I guess)

On the other hand, I guess allowing winblend to be a function could be a decent compromise:
```lua
winblend = function() return vim.o.winblend end
```

**Comment by Conni2461** [comment]
would you be interested in opening a PR? i would accept one :) most "breaking" changes to current master are fine because we still have a stable release. 

> IMO this is almost a bug

then why open a Feature request?! just saying

**Comment by lrfurtado** [comment]
![image](https://github.com/nvim-telescope/telescope.nvim/assets/943194/3df7cfc5-f712-48c7-bda0-0186a7d25968)

this seems like os aready implememented should we close it ? @Conni2461 ?

**Comment by Conni2461** [comment]
no this is not fixed. what you are looking at is the which_key action (which already does this correctly) - keymap help menu.

It needs to be fixed here: https://github.com/nvim-telescope/telescope.nvim/blob/20bf20500c95208c3ac0ef07245065bf94dcab15/lua/telescope/pickers.lua#L306

**Comment by brianaung** [comment]
> what you are looking at is the which_key action (which already does this correctly)

doesn't it also have the same issue? if `opts.winblend` is nil it will fallback to the default value which is 0 (or whatever user set in telescope setup call). Instead, we want to default to `vim.o.winblend` instead of 0 if I'm understanding this correctly? 

if that's the case, would changing this to `vim.o.winblend` works?
https://github.com/nvim-telescope/telescope.nvim/blob/20bf20500c95208c3ac0ef07245065bf94dcab15/lua/telescope/config.lua#L222
the problem with this though is whenever user `set winblend` after loading telescope, this new value won't be reflected since `telescope.config` won't get reloaded?

i'm not very experienced with this so if anything i said is wrong sorry =).

**Comment by Conni2461** [comment]
the issue should be solved with https://github.com/nvim-telescope/telescope.nvim/pull/2861 can someone confirm

and yes the issue also existed with `which_key` action

**Comment by nettrino** [comment]
Still encountered this issue with 
```
Error executing Lua callback: ...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:333: Option 'winblend' value must be Integer
stack traceback:
        [C]: in function 'nvim_win_set_option'
        ...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:333: in function '_create_window'
        ...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:382: in function 'find'
        ...im/lazy/telescope.nvim/lua/telescope/builtin/__files.lua:350: in function 'v'
        ...im/lazy/telescope.nvim/lua/telescope/builtin/__files.lua:595: in function 'v'
        ...cker/start/telescope.nvim/lua/telescope/builtin/init.lua:578: in function <...cker/start/telescope.nvim/lua/telescope/builtin/init.lua:537>
        ...share/nvim/lazy/telescope.nvim/lua/telescope/command.lua:188: in function 'run_command'
        ...share/nvim/lazy/telescope.nvim/lua/telescope/command.lua:259: in function 'load_command'
        ...ocal/share/nvim/lazy/telescope.nvim/plugin/telescope.lua:108: in function <...ocal/share/nvim/lazy/telescope.nvim/plugin/telescope.lua:107>
```
_checking to see if its a matter of an old version_

**Comment by MannyFay** [comment]
This is a problem with Which-Key-Plugin.
I've re-wright my Nvim environment to Lazy at the moment. My setup is by now super basic:
- Lazy
- Color scheme
- nvim-tree
- telescope
- which-key

...and a few options and key mappings.

If I use Which-Key and run Telescope:
```shell
E5108: Error executing lua ...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:333: Option 'winblend' value must be Integer
stack traceback:
        [C]: in function 'nvim_win_set_option'
        ...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:333: in function '_create_window'
        ...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:382: in function 'find'
        ...im/lazy/telescope.nvim/lua/telescope/builtin/__files.lua:350: in function 'v'
        ...im/lazy/telescope.nvim/lua/telescope/builtin/__files.lua:595: in function 'v'
        .../nvim/lazy/telescope.nvim/lua/telescope/builtin/init.lua:542: in function 'find_files'
        [string ":lua"]:1: in main chunk
```
Without Which-Key, Telescope runs well.
I've tried it with `vim.opt.winblend = 0` in my options file, but it didn't work.

Is there any solution or recommendation to fix this?

**Comment by Conni2461** [comment]
can you open a new issue with a minimal reproducible config? otherwise it will be hard to help you. thanks :)
