### ISSUE TITLE
Neovim Nightly - incorrect search

### ISSUE THREAD

**Issue by wojciech-kulik** [nvim-telescope/telescope.nvim#2993]
### Description

On the latest Neovim Nightly, search doesn't work properly. The same issue doesn't occur on the stable 0.9.5. version

### Neovim version

```markdown
NVIM v0.10.0-dev-2657+g9765efb40
Build type: RelWithDebInfo
LuaJIT 2.1.1710088188
```

### Operating system and version

macOS 14.4

### Telescope version / branch / rev

main

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0
- OK fd: found fd 9.0.0

===== Installed extensions ===== ~

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `live_grep_args` ~
- No healthcheck provided

Telescope Extension: `ui-select` ~
- No healthcheck provided
```

### Steps to reproduce

```
Telescope find_files theme=dropdown previewer=false
```

https://github.com/nvim-telescope/telescope.nvim/assets/3128467/3ca98404-ae31-4ecd-a697-ce4cd4383bf3

### Actual behavior

Some results are missing, one time they appear, another time they don't. Looks like some problem with rendering?

**Comment by jamestrew** [comment]
I think this was fixed in https://github.com/nvim-telescope/telescope.nvim/pull/2986
Let me know if that is not the case, I can re-open and investigate more but I'm not able to reproduce it currently.

**Comment by wojciech-kulik** [comment]
@jamestrew I encountered this issue after this fix. Also, just to confirm I installed latest Neovim Nightly + latest Telescope and it still occurs.

**Comment by jamestrew** [comment]
I'm also on neovim nightly, latest commit as of writing and telescope master HEAD but I'm still not able to reproduce.

Please try with this config:
```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "nvim-telescope/telescope.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
    },
    config = function()
      require("telescope").setup({})
    end,
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```
You can save this to some temp directory as `min.lua` and launch `nvim --clean -u min.lua`.

**Comment by michaelcosj** [comment]
I'm also having the same issue. Seems to only happen for me when theme is set to dropdown but I'm unable to reproduce with the minimal config above

**Comment by jamestrew** [comment]
Yeah I'm trying with the dropdown theme with this minimal config.

**Comment by wojciech-kulik** [comment]
This is super weird, I can't reproduce it with `min.lua` I even copied my whole telescope config + catppuccin. Still no luck.

**Comment by wojciech-kulik** [comment]
I removed every file from my config leaving just `telescope.lua` and `lazy.lua` and it's still reproducible :D

**Comment by jamestrew** [comment]
Can you go to your telescope installation directory and just double check the commit there and that you're definitely at master HEAD (or at least past #2986)

It wouldn't be the first time someone thought they had a fix that they didn't have due to something blocking the package manager from updating a plugin.

**Comment by wojciech-kulik** [comment]
ahhhh..... I had `branch = "0.1.x"` and this fix is not yet released. I never use `branch`, I just copied it in this case from the README some long time ago :D,  that's why I haven't thought about it.

Now it works with the latest plugin version 🎊

**Comment by michaelcosj** [comment]
I checked now and I was on the 0.1.x branch not master. I updated and it's fixed

**Comment by jamestrew** [comment]
Cool glad to hear we don't have some super mystery bug on our hands 😁

I'll close the issue 👍

**Comment by wojciech-kulik** [comment]
@jamestrew Thank you for the help, checking git and the current commit was a good hint!
