### ISSUE TITLE
preview vim_buffer lnum issue

### ISSUE THREAD

**Issue by polarmutex** [nvim-telescope/telescope.nvim#33]
in the previewer vim_buffer, it subtracts 1 from the entry.lnum when highlighting the entry. This is probably done for the LSP document symbol builtin. The subtract 1 should be done when making entries for the LSP document symbols and not in the previewer

**Comment by tami5** [comment]
Is this still ongoing bug? @rockerBOO @bryall

**Comment by bryall** [comment]
it still exists in the code,  basically the minus one in the buffer previewer needs to be removed and then double check all who use the buffer previewer to check to make sure they have the correct modifications when creating their entries

**Comment by Conni2461** [comment]
Previewers got completely rewritten and that should be fixed now. Can you confirm? Thanks :)

**Comment by bryall** [comment]
this bug is still present,

on line 535 in the make_entries file, the tree sitter has to do a "entry.lnum - 1" to have the correct line number. tree sitter should not have to do this.

**Comment by Conni2461** [comment]
Okay so now its tree-sitter :) I agree with you that should not happen here.
But buffer and lsp work should be good right?

**Comment by tjdevries** [comment]
Any problems with this now? Or can we close?

**Comment by bryall** [comment]
this issue was created because we had to add 1 to the line number when making entries. As far as I know we still need it for tree sitter to work correctly. If my memory remembers correctly, Lsp needed to subtract one when making entries and this plus one was to overcome it.

I am find if you want to close this issue, since it is working, the issue was created to make the code better and more clear

https://github.com/nvim-telescope/telescope.nvim/blob/9f58834d04eca69600c132fe4600bbccf7bb9463/lua/telescope/make_entry.lua#L584

**Comment by Conni2461** [comment]
Closing this issue, its too general and we have no `+ 1`s left in the previewer that are an issue. 

The `treesitter` +1 is still there but its inevitable and the lsp stuff does not have any `-1` afaik
