### ISSUE TITLE
lsp_document_symbols breaks for some elixir language server entries

### ISSUE THREAD

**Issue by skbolton** [nvim-telescope/telescope.nvim#874]
### Description
Using `telescope.builtin.lsp_document_symbols()` with my elixir language results in errors.
 
**Expected Behavior**
Running `telescope.builtin.lsp_document_symbols()` should return the symbols for the file

**Actual Behavior**
An error is produced.

### Details

Here is the error that is produced when I try to use telescope to get document symbols.

```
E5108: Error executing lua ...pack/packer/start/telescope/lua/telescope/make_entry.lua:428: attempt to concatenate local 'symbol_type' (a nil value)
```

When I adjusted the source code of telescope to print out the entry that is causing the failure. I get this entry

```
[Event] get_next_page(uuid, %{after: integer | nil, before: integer | nil, first: integer | nil, last: integer | nil})-
```

I am guessing that the pattern used in make_entry.lua:420 needs to adjusted to handle a pattern presented here. I am not completely familiar with the matching patterns of Lua but could make a fix with a suggestion on what should be done.

I played around with some files that have very few symbols in elixir and things will work. Also my golang server has no issues, just something about this elixir pattern.

<details><summary>Environment</summary>

- nvim --version output: v0.5.0-dev+1342-gde96626ad
- Operating system: Arch Linux
- Telescope commit: ec8cf12

</details>

**Comment by Conni2461** [comment]
Should be fixed by https://github.com/nvim-telescope/telescope.nvim/commit/d2b3b080777099d89f396fe949d30e6eceeb4370

Closing for now

**Comment by skbolton** [comment]
Issue still remains for me. In my case its choking on symbol name not symbol type being nil.

**Comment by Conni2461** [comment]
Hmm okay the regex above is probably wrong

**Comment by skbolton** [comment]
The issue is occurirng at this [line](https://github.com/nvim-telescope/telescope.nvim/blob/6ac5ee0854fe02d651cadf2fc97a2463ff92f322/lua/telescope/make_entry.lua#L414). In Elixir the `|` character shows up in the entries such as the one I posted
```
[Event] get_next_page(uuid, %{after: integer | nil, before: integer | nil, first: integer | nil, last: integer | nil})-
```

That line ends up making that entry be `nil})` which gets passed into the next line that is matching on symbol name and symbol type. I am not picking up on why this sub needs to happen.

**Comment by skbolton** [comment]
bump @Conni2461 sorry to bug you but I'd like to get this fixed. I have a branch that changes the substitution to not remove `|` and nothing has broken for me but I am sure there are details I don't know about.

**Comment by lATAl** [comment]
@skbolton do you have any solution? I also get this error on elixir

**Comment by skbolton** [comment]
The issue is mentioned [here](https://github.com/nvim-telescope/telescope.nvim/issues/874#issuecomment-866617660) I had a fork of telescope that removed the substitution of `|` and nothing seemed to break but I am not sure what that line is trying to do. I am waiting on feedback on the reasons for this logic. If you want to fix this then you can get rid of that substitution and see if it fixes things for you.

**Comment by fdschmidt93** [comment]
> I am waiting on feedback on the reasons for this logic. 

Why not a PR? I'm not sure any maintainer is using Elixir.

**Comment by skbolton** [comment]
> > I am waiting on feedback on the reasons for this logic.
> 
> Why not a PR? I'm not sure any maintainer is using Elixir.

My PR would only remove a line that has some sort of reason for being present. I was waiting for feedback of what feature/reason it has for being there before just chopping it off.

**Comment by monooso** [comment]
Perhaps @sunjon can help here, as he added the code in question. I'm encountering this problem quite frequently on my Elixir projects.

**Comment by romariolopezc** [comment]
@skbolton where can I find your fork? 

I'm having this issue as well

**Comment by nifoc** [comment]
Sorry for tagging you, @Conni2461.

I'm very interested in fixing this, especially since this has been broken for so long. Would a PR that simply removes the `|` substitution be okay?

**Comment by Conni2461** [comment]
I dont know what this regex does or why its here. But you can open a PR and we can merge it and see.
